-- Create the core monolith schema
-- - by Richard W.M. Jones <rich@annexia.org>
--
-- This library is free software; you can redistribute it and/or
-- modify it under the terms of the GNU Library General Public
-- License as published by the Free Software Foundation; either
-- version 2 of the License, or (at your option) any later version.
--
-- This library is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
-- Library General Public License for more details.
--
-- You should have received a copy of the GNU Library General Public
-- License along with this library; if not, write to the Free
-- Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
--
-- $Id: monolith_core_create.sql,v 1.2 2002/11/15 20:46:03 rich Exp $

begin work;

create table ml_countries
(
	code char(2)
		constraint ml_countries_code_nn
		not null,
	name text
		constraint ml_countries_name_nn
		not null,

	primary key (code)
);

create unique index ml_countries_name on ml_countries (name);

create table ml_timezones
(
	id int4
		constraint ml_timezones_id_nn
		not null,
	name text
		constraint ml_timezones_name_nn
		not null,
	countrycode char(2)
		constraint ml_timezones_countrycode_nn
		not null
		references ml_countries (code),

	primary key (id)
);

create unique index ml_timezones_name on ml_timezones (name);

-- Grant access to the tables by the webserver.

grant select on ml_countries to nobody;
grant select on ml_timezones to nobody;

-- Populate the tables.

insert into ml_countries (code,name) values ('AD','Andorra');
insert into ml_countries (code,name) values ('AE','United Arab Emirates');
insert into ml_countries (code,name) values ('AF','Afghanistan');
insert into ml_countries (code,name) values ('AG','Antigua and Barbuda');
insert into ml_countries (code,name) values ('AI','Anguilla');
insert into ml_countries (code,name) values ('AL','Albania');
insert into ml_countries (code,name) values ('AM','Armenia');
insert into ml_countries (code,name) values ('AN','Netherlands Antilles');
insert into ml_countries (code,name) values ('AO','Angola');
insert into ml_countries (code,name) values ('AQ','Antarctica');
insert into ml_countries (code,name) values ('AR','Argentina');
insert into ml_countries (code,name) values ('AS','American Samoa');
insert into ml_countries (code,name) values ('AT','Austria');
insert into ml_countries (code,name) values ('AU','Australia');
insert into ml_countries (code,name) values ('AW','Aruba');
insert into ml_countries (code,name) values ('AZ','Azerbaijan');
insert into ml_countries (code,name) values ('BA','Bosnia and Herzegovina');
insert into ml_countries (code,name) values ('BB','Barbados');
insert into ml_countries (code,name) values ('BD','Bangladesh');
insert into ml_countries (code,name) values ('BE','Belgium');
insert into ml_countries (code,name) values ('BF','Burkina Faso');
insert into ml_countries (code,name) values ('BG','Bulgaria');
insert into ml_countries (code,name) values ('BH','Bahrain');
insert into ml_countries (code,name) values ('BI','Burundi');
insert into ml_countries (code,name) values ('BJ','Benin');
insert into ml_countries (code,name) values ('BM','Bermuda');
insert into ml_countries (code,name) values ('BN','Brunei Darussalam');
insert into ml_countries (code,name) values ('BO','Bolivia');
insert into ml_countries (code,name) values ('BR','Brazil');
insert into ml_countries (code,name) values ('BS','Bahamas');
insert into ml_countries (code,name) values ('BT','Bhutan');
insert into ml_countries (code,name) values ('BV','Bouvet Island');
insert into ml_countries (code,name) values ('BW','Botswana');
insert into ml_countries (code,name) values ('BY','Belarus');
insert into ml_countries (code,name) values ('BZ','Belize');
insert into ml_countries (code,name) values ('CA','Canada');
insert into ml_countries (code,name) values ('CC','Cocos (Keeling) Islands');
insert into ml_countries (code,name) values ('CD','Congo, The Democratic Republic of The');
insert into ml_countries (code,name) values ('CF','Central African Republic');
insert into ml_countries (code,name) values ('CG','Congo');
insert into ml_countries (code,name) values ('CH','Switzerland');
insert into ml_countries (code,name) values ('CI','Cote D''Ivoire');
insert into ml_countries (code,name) values ('CK','Cook Islands');
insert into ml_countries (code,name) values ('CL','Chile');
insert into ml_countries (code,name) values ('CM','Cameroon');
insert into ml_countries (code,name) values ('CN','China');
insert into ml_countries (code,name) values ('CO','Colombia');
insert into ml_countries (code,name) values ('CR','Costa Rica');
insert into ml_countries (code,name) values ('CU','Cuba');
insert into ml_countries (code,name) values ('CV','Cape Verde');
insert into ml_countries (code,name) values ('CX','Christmas Island');
insert into ml_countries (code,name) values ('CY','Cyprus');
insert into ml_countries (code,name) values ('CZ','Czech Republic');
insert into ml_countries (code,name) values ('DE','Germany');
insert into ml_countries (code,name) values ('DJ','Djibouti');
insert into ml_countries (code,name) values ('DK','Denmark');
insert into ml_countries (code,name) values ('DM','Dominica');
insert into ml_countries (code,name) values ('DO','Dominican Republic');
insert into ml_countries (code,name) values ('DZ','Algeria');
insert into ml_countries (code,name) values ('EC','Ecuador');
insert into ml_countries (code,name) values ('EE','Estonia');
insert into ml_countries (code,name) values ('EG','Egypt');
insert into ml_countries (code,name) values ('EH','Western Sahara');
insert into ml_countries (code,name) values ('ER','Eritrea');
insert into ml_countries (code,name) values ('ES','Spain');
insert into ml_countries (code,name) values ('ET','Ethiopia');
insert into ml_countries (code,name) values ('FI','Finland');
insert into ml_countries (code,name) values ('FJ','Fiji');
insert into ml_countries (code,name) values ('FK','Falkland Islands (Malvinas)');
insert into ml_countries (code,name) values ('FM','Micronesia, Federated States of');
insert into ml_countries (code,name) values ('FO','Faroe Islands');
insert into ml_countries (code,name) values ('FR','France');
insert into ml_countries (code,name) values ('GA','Gabon');
insert into ml_countries (code,name) values ('GB','United Kingdom');
insert into ml_countries (code,name) values ('GD','Grenada');
insert into ml_countries (code,name) values ('GE','Georgia');
insert into ml_countries (code,name) values ('GF','French Guiana');
insert into ml_countries (code,name) values ('GH','Ghana');
insert into ml_countries (code,name) values ('GI','Gibraltar');
insert into ml_countries (code,name) values ('GL','Greenland');
insert into ml_countries (code,name) values ('GM','Gambia');
insert into ml_countries (code,name) values ('GN','Guinea');
insert into ml_countries (code,name) values ('GP','Guadeloupe');
insert into ml_countries (code,name) values ('GQ','Equatorial Guinea');
insert into ml_countries (code,name) values ('GR','Greece');
insert into ml_countries (code,name) values ('GS','South Georgia and The South Sandwich Islands');
insert into ml_countries (code,name) values ('GT','Guatemala');
insert into ml_countries (code,name) values ('GU','Guam');
insert into ml_countries (code,name) values ('GW','Guinea-Bissau');
insert into ml_countries (code,name) values ('GY','Guyana');
insert into ml_countries (code,name) values ('HK','Hong Kong');
insert into ml_countries (code,name) values ('HM','Heard Island and McDonald Islands');
insert into ml_countries (code,name) values ('HN','Honduras');
insert into ml_countries (code,name) values ('HR','Croatia');
insert into ml_countries (code,name) values ('HT','Haiti');
insert into ml_countries (code,name) values ('HU','Hungary');
insert into ml_countries (code,name) values ('ID','Indonesia');
insert into ml_countries (code,name) values ('IE','Ireland');
insert into ml_countries (code,name) values ('IL','Israel');
insert into ml_countries (code,name) values ('IN','India');
insert into ml_countries (code,name) values ('IO','British Indian Ocean Territory');
insert into ml_countries (code,name) values ('IQ','Iraq');
insert into ml_countries (code,name) values ('IR','Iran, Islamic Republic of');
insert into ml_countries (code,name) values ('IS','Iceland');
insert into ml_countries (code,name) values ('IT','Italy');
insert into ml_countries (code,name) values ('JM','Jamaica');
insert into ml_countries (code,name) values ('JO','Jordan');
insert into ml_countries (code,name) values ('JP','Japan');
insert into ml_countries (code,name) values ('KE','Kenya');
insert into ml_countries (code,name) values ('KG','Kyrgyzstan');
insert into ml_countries (code,name) values ('KH','Cambodia');
insert into ml_countries (code,name) values ('KI','Kiribati');
insert into ml_countries (code,name) values ('KM','Comoros');
insert into ml_countries (code,name) values ('KN','Saint Kitts and Nevis');
insert into ml_countries (code,name) values ('KP','Korea, Democratic People''s Republic of');
insert into ml_countries (code,name) values ('KR','Korea, Republic of');
insert into ml_countries (code,name) values ('KW','Kuwait');
insert into ml_countries (code,name) values ('KY','Cayman Islands');
insert into ml_countries (code,name) values ('KZ','Kazakstan');
insert into ml_countries (code,name) values ('LA','Lao People''s Democratic Republic');
insert into ml_countries (code,name) values ('LB','Lebanon');
insert into ml_countries (code,name) values ('LC','Saint Lucia');
insert into ml_countries (code,name) values ('LI','Liechtenstein');
insert into ml_countries (code,name) values ('LK','Sri Lanka');
insert into ml_countries (code,name) values ('LR','Liberia');
insert into ml_countries (code,name) values ('LS','Lesotho');
insert into ml_countries (code,name) values ('LT','Lithuania');
insert into ml_countries (code,name) values ('LU','Luxembourg');
insert into ml_countries (code,name) values ('LV','Latvia');
insert into ml_countries (code,name) values ('LY','Libyan Arab Jamahiriya');
insert into ml_countries (code,name) values ('MA','Morocco');
insert into ml_countries (code,name) values ('MC','Monaco');
insert into ml_countries (code,name) values ('MD','Moldova, Republic of');
insert into ml_countries (code,name) values ('MG','Madagascar');
insert into ml_countries (code,name) values ('MH','Marshall Islands');
insert into ml_countries (code,name) values ('MK','Macedonia, The Former Yugoslav Republic of');
insert into ml_countries (code,name) values ('ML','Mali');
insert into ml_countries (code,name) values ('MM','Myanmar');
insert into ml_countries (code,name) values ('MN','Mongolia');
insert into ml_countries (code,name) values ('MO','Macau');
insert into ml_countries (code,name) values ('MP','Northern Mariana Islands');
insert into ml_countries (code,name) values ('MQ','Martinique');
insert into ml_countries (code,name) values ('MR','Mauritania');
insert into ml_countries (code,name) values ('MS','Montserrat');
insert into ml_countries (code,name) values ('MT','Malta');
insert into ml_countries (code,name) values ('MU','Mauritius');
insert into ml_countries (code,name) values ('MV','Maldives');
insert into ml_countries (code,name) values ('MW','Malawi');
insert into ml_countries (code,name) values ('MX','Mexico');
insert into ml_countries (code,name) values ('MY','Malaysia');
insert into ml_countries (code,name) values ('MZ','Mozambique');
insert into ml_countries (code,name) values ('NA','Namibia');
insert into ml_countries (code,name) values ('NC','New Caledonia');
insert into ml_countries (code,name) values ('NE','Niger');
insert into ml_countries (code,name) values ('NF','Norfolk Island');
insert into ml_countries (code,name) values ('NG','Nigeria');
insert into ml_countries (code,name) values ('NI','Nicaragua');
insert into ml_countries (code,name) values ('NL','Netherlands');
insert into ml_countries (code,name) values ('NO','Norway');
insert into ml_countries (code,name) values ('NP','Nepal');
insert into ml_countries (code,name) values ('NR','Nauru');
insert into ml_countries (code,name) values ('NU','Niue');
insert into ml_countries (code,name) values ('NZ','New Zealand');
insert into ml_countries (code,name) values ('OM','Oman');
insert into ml_countries (code,name) values ('PA','Panama');
insert into ml_countries (code,name) values ('PE','Peru');
insert into ml_countries (code,name) values ('PF','French Polynesia');
insert into ml_countries (code,name) values ('PG','Papua New Guinea');
insert into ml_countries (code,name) values ('PH','Philippines');
insert into ml_countries (code,name) values ('PK','Pakistan');
insert into ml_countries (code,name) values ('PL','Poland');
insert into ml_countries (code,name) values ('PM','Saint Pierre and Miquelon');
insert into ml_countries (code,name) values ('PN','Pitcairn');
insert into ml_countries (code,name) values ('PR','Puerto Rico');
insert into ml_countries (code,name) values ('PS','Palestinian Territory, Occupied');
insert into ml_countries (code,name) values ('PT','Portugal');
insert into ml_countries (code,name) values ('PW','Palau');
insert into ml_countries (code,name) values ('PY','Paraguay');
insert into ml_countries (code,name) values ('QA','Qatar');
insert into ml_countries (code,name) values ('RE','Reunion');
insert into ml_countries (code,name) values ('RO','Romania');
insert into ml_countries (code,name) values ('RU','Russian Federation');
insert into ml_countries (code,name) values ('RW','Rwanda');
insert into ml_countries (code,name) values ('SA','Saudi Arabia');
insert into ml_countries (code,name) values ('SB','Solomon Islands');
insert into ml_countries (code,name) values ('SC','Seychelles');
insert into ml_countries (code,name) values ('SD','Sudan');
insert into ml_countries (code,name) values ('SE','Sweden');
insert into ml_countries (code,name) values ('SG','Singapore');
insert into ml_countries (code,name) values ('SH','Saint Helena');
insert into ml_countries (code,name) values ('SI','Slovenia');
insert into ml_countries (code,name) values ('SJ','Svalbard and Jan Mayen');
insert into ml_countries (code,name) values ('SK','Slovakia');
insert into ml_countries (code,name) values ('SL','Sierra Leone');
insert into ml_countries (code,name) values ('SM','San Marino');
insert into ml_countries (code,name) values ('SN','Senegal');
insert into ml_countries (code,name) values ('SO','Somalia');
insert into ml_countries (code,name) values ('SR','Suriname');
insert into ml_countries (code,name) values ('ST','Sao Tome and Principe');
insert into ml_countries (code,name) values ('SV','El Salvador');
insert into ml_countries (code,name) values ('SY','Syrian Arab Republic');
insert into ml_countries (code,name) values ('SZ','Swaziland');
insert into ml_countries (code,name) values ('TC','Turks and Caicos Islands');
insert into ml_countries (code,name) values ('TD','Chad');
insert into ml_countries (code,name) values ('TF','French Southern Territories');
insert into ml_countries (code,name) values ('TG','Togo');
insert into ml_countries (code,name) values ('TH','Thailand');
insert into ml_countries (code,name) values ('TJ','Tajikistan');
insert into ml_countries (code,name) values ('TK','Tokelau');
insert into ml_countries (code,name) values ('TM','Turkmenistan');
insert into ml_countries (code,name) values ('TN','Tunisia');
insert into ml_countries (code,name) values ('TO','Tonga');
insert into ml_countries (code,name) values ('TP','East Timor');
insert into ml_countries (code,name) values ('TR','Turkey');
insert into ml_countries (code,name) values ('TT','Trinidad and Tobago');
insert into ml_countries (code,name) values ('TV','Tuvalu');
insert into ml_countries (code,name) values ('TW','Taiwan, Province of China');
insert into ml_countries (code,name) values ('TZ','Tanzania, United Republic of');
insert into ml_countries (code,name) values ('UA','Ukraine');
insert into ml_countries (code,name) values ('UG','Uganda');
insert into ml_countries (code,name) values ('UM','United States Minor Outlying Islands');
insert into ml_countries (code,name) values ('US','United States');
insert into ml_countries (code,name) values ('UY','Uruguay');
insert into ml_countries (code,name) values ('UZ','Uzbekistan');
insert into ml_countries (code,name) values ('VA','Holy See (Vatican City State)');
insert into ml_countries (code,name) values ('VC','Saint Vincent and The Grenadines');
insert into ml_countries (code,name) values ('VE','Venezuela');
insert into ml_countries (code,name) values ('VG','Virgin Islands, British');
insert into ml_countries (code,name) values ('VI','Virgin Islands, U.S.');
insert into ml_countries (code,name) values ('VN','Viet Nam');
insert into ml_countries (code,name) values ('VU','Vanuatu');
insert into ml_countries (code,name) values ('WF','Wallis and Futuna');
insert into ml_countries (code,name) values ('WS','Samoa');
insert into ml_countries (code,name) values ('YE','Yemen');
insert into ml_countries (code,name) values ('YT','Mayotte');
insert into ml_countries (code,name) values ('YU','Yugoslavia');
insert into ml_countries (code,name) values ('ZA','South Africa');
insert into ml_countries (code,name) values ('ZM','Zambia');
insert into ml_countries (code,name) values ('ZW','Zimbabwe');

insert into ml_timezones (countrycode,id,name) values ('AD','1','Europe/Andorra');
insert into ml_timezones (countrycode,id,name) values ('AE','2','Asia/Dubai');
insert into ml_timezones (countrycode,id,name) values ('AF','3','Asia/Kabul');
insert into ml_timezones (countrycode,id,name) values ('AG','4','America/Antigua');
insert into ml_timezones (countrycode,id,name) values ('AI','5','America/Anguilla');
insert into ml_timezones (countrycode,id,name) values ('AL','6','Europe/Tirane');
insert into ml_timezones (countrycode,id,name) values ('AM','7','Asia/Yerevan');
insert into ml_timezones (countrycode,id,name) values ('AN','8','America/Curacao');
insert into ml_timezones (countrycode,id,name) values ('AO','9','Africa/Luanda');
insert into ml_timezones (countrycode,id,name) values ('AQ','10','Antarctica/McMurdo');
insert into ml_timezones (countrycode,id,name) values ('AQ','11','Antarctica/South_Pole');
insert into ml_timezones (countrycode,id,name) values ('AQ','12','Antarctica/Palmer');
insert into ml_timezones (countrycode,id,name) values ('AQ','13','Antarctica/Mawson');
insert into ml_timezones (countrycode,id,name) values ('AQ','14','Antarctica/Davis');
insert into ml_timezones (countrycode,id,name) values ('AQ','15','Antarctica/Casey');
insert into ml_timezones (countrycode,id,name) values ('AQ','16','Antarctica/Vostok');
insert into ml_timezones (countrycode,id,name) values ('AQ','17','Antarctica/DumontDUrville');
insert into ml_timezones (countrycode,id,name) values ('AQ','18','Antarctica/Syowa');
insert into ml_timezones (countrycode,id,name) values ('AR','19','America/Buenos_Aires');
insert into ml_timezones (countrycode,id,name) values ('AR','20','America/Rosario');
insert into ml_timezones (countrycode,id,name) values ('AR','21','America/Cordoba');
insert into ml_timezones (countrycode,id,name) values ('AR','22','America/Jujuy');
insert into ml_timezones (countrycode,id,name) values ('AR','23','America/Catamarca');
insert into ml_timezones (countrycode,id,name) values ('AR','24','America/Mendoza');
insert into ml_timezones (countrycode,id,name) values ('AS','25','Pacific/Pago_Pago');
insert into ml_timezones (countrycode,id,name) values ('AT','26','Europe/Vienna');
insert into ml_timezones (countrycode,id,name) values ('AU','27','Australia/Lord_Howe');
insert into ml_timezones (countrycode,id,name) values ('AU','28','Australia/Hobart');
insert into ml_timezones (countrycode,id,name) values ('AU','29','Australia/Melbourne');
insert into ml_timezones (countrycode,id,name) values ('AU','30','Australia/Sydney');
insert into ml_timezones (countrycode,id,name) values ('AU','31','Australia/Broken_Hill');
insert into ml_timezones (countrycode,id,name) values ('AU','32','Australia/Brisbane');
insert into ml_timezones (countrycode,id,name) values ('AU','33','Australia/Lindeman');
insert into ml_timezones (countrycode,id,name) values ('AU','34','Australia/Adelaide');
insert into ml_timezones (countrycode,id,name) values ('AU','35','Australia/Darwin');
insert into ml_timezones (countrycode,id,name) values ('AU','36','Australia/Perth');
insert into ml_timezones (countrycode,id,name) values ('AW','37','America/Aruba');
insert into ml_timezones (countrycode,id,name) values ('AZ','38','Asia/Baku');
insert into ml_timezones (countrycode,id,name) values ('BA','39','Europe/Sarajevo');
insert into ml_timezones (countrycode,id,name) values ('BB','40','America/Barbados');
insert into ml_timezones (countrycode,id,name) values ('BD','41','Asia/Dhaka');
insert into ml_timezones (countrycode,id,name) values ('BE','42','Europe/Brussels');
insert into ml_timezones (countrycode,id,name) values ('BF','43','Africa/Ouagadougou');
insert into ml_timezones (countrycode,id,name) values ('BG','44','Europe/Sofia');
insert into ml_timezones (countrycode,id,name) values ('BH','45','Asia/Bahrain');
insert into ml_timezones (countrycode,id,name) values ('BI','46','Africa/Bujumbura');
insert into ml_timezones (countrycode,id,name) values ('BJ','47','Africa/Porto-Novo');
insert into ml_timezones (countrycode,id,name) values ('BM','48','Atlantic/Bermuda');
insert into ml_timezones (countrycode,id,name) values ('BN','49','Asia/Brunei');
insert into ml_timezones (countrycode,id,name) values ('BO','50','America/La_Paz');
insert into ml_timezones (countrycode,id,name) values ('BR','51','America/Noronha');
insert into ml_timezones (countrycode,id,name) values ('BR','52','America/Belem');
insert into ml_timezones (countrycode,id,name) values ('BR','53','America/Fortaleza');
insert into ml_timezones (countrycode,id,name) values ('BR','54','America/Recife');
insert into ml_timezones (countrycode,id,name) values ('BR','55','America/Araguaina');
insert into ml_timezones (countrycode,id,name) values ('BR','56','America/Maceio');
insert into ml_timezones (countrycode,id,name) values ('BR','57','America/Sao_Paulo');
insert into ml_timezones (countrycode,id,name) values ('BR','58','America/Cuiaba');
insert into ml_timezones (countrycode,id,name) values ('BR','59','America/Porto_Velho');
insert into ml_timezones (countrycode,id,name) values ('BR','60','America/Boa_Vista');
insert into ml_timezones (countrycode,id,name) values ('BR','61','America/Manaus');
insert into ml_timezones (countrycode,id,name) values ('BR','62','America/Eirunepe');
insert into ml_timezones (countrycode,id,name) values ('BR','63','America/Rio_Branco');
insert into ml_timezones (countrycode,id,name) values ('BS','64','America/Nassau');
insert into ml_timezones (countrycode,id,name) values ('BT','65','Asia/Thimphu');
insert into ml_timezones (countrycode,id,name) values ('BW','66','Africa/Gaborone');
insert into ml_timezones (countrycode,id,name) values ('BY','67','Europe/Minsk');
insert into ml_timezones (countrycode,id,name) values ('BZ','68','America/Belize');
insert into ml_timezones (countrycode,id,name) values ('CA','69','America/St_Johns');
insert into ml_timezones (countrycode,id,name) values ('CA','70','America/Halifax');
insert into ml_timezones (countrycode,id,name) values ('CA','71','America/Glace_Bay');
insert into ml_timezones (countrycode,id,name) values ('CA','72','America/Goose_Bay');
insert into ml_timezones (countrycode,id,name) values ('CA','73','America/Montreal');
insert into ml_timezones (countrycode,id,name) values ('CA','74','America/Nipigon');
insert into ml_timezones (countrycode,id,name) values ('CA','75','America/Thunder_Bay');
insert into ml_timezones (countrycode,id,name) values ('CA','76','America/Pangnirtung');
insert into ml_timezones (countrycode,id,name) values ('CA','77','America/Iqaluit');
insert into ml_timezones (countrycode,id,name) values ('CA','78','America/Rankin_Inlet');
insert into ml_timezones (countrycode,id,name) values ('CA','79','America/Winnipeg');
insert into ml_timezones (countrycode,id,name) values ('CA','80','America/Rainy_River');
insert into ml_timezones (countrycode,id,name) values ('CA','81','America/Cambridge_Bay');
insert into ml_timezones (countrycode,id,name) values ('CA','82','America/Regina');
insert into ml_timezones (countrycode,id,name) values ('CA','83','America/Swift_Current');
insert into ml_timezones (countrycode,id,name) values ('CA','84','America/Edmonton');
insert into ml_timezones (countrycode,id,name) values ('CA','85','America/Yellowknife');
insert into ml_timezones (countrycode,id,name) values ('CA','86','America/Inuvik');
insert into ml_timezones (countrycode,id,name) values ('CA','87','America/Dawson_Creek');
insert into ml_timezones (countrycode,id,name) values ('CA','88','America/Vancouver');
insert into ml_timezones (countrycode,id,name) values ('CA','89','America/Whitehorse');
insert into ml_timezones (countrycode,id,name) values ('CA','90','America/Dawson');
insert into ml_timezones (countrycode,id,name) values ('CC','91','Indian/Cocos');
insert into ml_timezones (countrycode,id,name) values ('CD','92','Africa/Kinshasa');
insert into ml_timezones (countrycode,id,name) values ('CD','93','Africa/Lubumbashi');
insert into ml_timezones (countrycode,id,name) values ('CF','94','Africa/Bangui');
insert into ml_timezones (countrycode,id,name) values ('CG','95','Africa/Brazzaville');
insert into ml_timezones (countrycode,id,name) values ('CH','96','Europe/Zurich');
insert into ml_timezones (countrycode,id,name) values ('CI','97','Africa/Abidjan');
insert into ml_timezones (countrycode,id,name) values ('CK','98','Pacific/Rarotonga');
insert into ml_timezones (countrycode,id,name) values ('CL','99','America/Santiago');
insert into ml_timezones (countrycode,id,name) values ('CL','100','Pacific/Easter');
insert into ml_timezones (countrycode,id,name) values ('CM','101','Africa/Douala');
insert into ml_timezones (countrycode,id,name) values ('CN','102','Asia/Harbin');
insert into ml_timezones (countrycode,id,name) values ('CN','103','Asia/Shanghai');
insert into ml_timezones (countrycode,id,name) values ('CN','104','Asia/Chungking');
insert into ml_timezones (countrycode,id,name) values ('CN','105','Asia/Urumqi');
insert into ml_timezones (countrycode,id,name) values ('CN','106','Asia/Kashgar');
insert into ml_timezones (countrycode,id,name) values ('CO','107','America/Bogota');
insert into ml_timezones (countrycode,id,name) values ('CR','108','America/Costa_Rica');
insert into ml_timezones (countrycode,id,name) values ('CU','109','America/Havana');
insert into ml_timezones (countrycode,id,name) values ('CV','110','Atlantic/Cape_Verde');
insert into ml_timezones (countrycode,id,name) values ('CX','111','Indian/Christmas');
insert into ml_timezones (countrycode,id,name) values ('CY','112','Asia/Nicosia');
insert into ml_timezones (countrycode,id,name) values ('CZ','113','Europe/Prague');
insert into ml_timezones (countrycode,id,name) values ('DE','114','Europe/Berlin');
insert into ml_timezones (countrycode,id,name) values ('DJ','115','Africa/Djibouti');
insert into ml_timezones (countrycode,id,name) values ('DK','116','Europe/Copenhagen');
insert into ml_timezones (countrycode,id,name) values ('DM','117','America/Dominica');
insert into ml_timezones (countrycode,id,name) values ('DO','118','America/Santo_Domingo');
insert into ml_timezones (countrycode,id,name) values ('DZ','119','Africa/Algiers');
insert into ml_timezones (countrycode,id,name) values ('EC','120','America/Guayaquil');
insert into ml_timezones (countrycode,id,name) values ('EC','121','Pacific/Galapagos');
insert into ml_timezones (countrycode,id,name) values ('EE','122','Europe/Tallinn');
insert into ml_timezones (countrycode,id,name) values ('EG','123','Africa/Cairo');
insert into ml_timezones (countrycode,id,name) values ('EH','124','Africa/El_Aaiun');
insert into ml_timezones (countrycode,id,name) values ('ER','125','Africa/Asmera');
insert into ml_timezones (countrycode,id,name) values ('ES','126','Europe/Madrid');
insert into ml_timezones (countrycode,id,name) values ('ES','127','Africa/Ceuta');
insert into ml_timezones (countrycode,id,name) values ('ES','128','Atlantic/Canary');
insert into ml_timezones (countrycode,id,name) values ('ET','129','Africa/Addis_Ababa');
insert into ml_timezones (countrycode,id,name) values ('FI','130','Europe/Helsinki');
insert into ml_timezones (countrycode,id,name) values ('FJ','131','Pacific/Fiji');
insert into ml_timezones (countrycode,id,name) values ('FK','132','Atlantic/Stanley');
insert into ml_timezones (countrycode,id,name) values ('FM','133','Pacific/Yap');
insert into ml_timezones (countrycode,id,name) values ('FM','134','Pacific/Truk');
insert into ml_timezones (countrycode,id,name) values ('FM','135','Pacific/Ponape');
insert into ml_timezones (countrycode,id,name) values ('FM','136','Pacific/Kosrae');
insert into ml_timezones (countrycode,id,name) values ('FO','137','Atlantic/Faeroe');
insert into ml_timezones (countrycode,id,name) values ('FR','138','Europe/Paris');
insert into ml_timezones (countrycode,id,name) values ('GA','139','Africa/Libreville');
insert into ml_timezones (countrycode,id,name) values ('GB','140','Europe/London');
insert into ml_timezones (countrycode,id,name) values ('GB','141','Europe/Belfast');
insert into ml_timezones (countrycode,id,name) values ('GD','142','America/Grenada');
insert into ml_timezones (countrycode,id,name) values ('GE','143','Asia/Tbilisi');
insert into ml_timezones (countrycode,id,name) values ('GF','144','America/Cayenne');
insert into ml_timezones (countrycode,id,name) values ('GH','145','Africa/Accra');
insert into ml_timezones (countrycode,id,name) values ('GI','146','Europe/Gibraltar');
insert into ml_timezones (countrycode,id,name) values ('GL','147','America/Scoresbysund');
insert into ml_timezones (countrycode,id,name) values ('GL','148','America/Godthab');
insert into ml_timezones (countrycode,id,name) values ('GL','149','America/Thule');
insert into ml_timezones (countrycode,id,name) values ('GM','150','Africa/Banjul');
insert into ml_timezones (countrycode,id,name) values ('GN','151','Africa/Conakry');
insert into ml_timezones (countrycode,id,name) values ('GP','152','America/Guadeloupe');
insert into ml_timezones (countrycode,id,name) values ('GQ','153','Africa/Malabo');
insert into ml_timezones (countrycode,id,name) values ('GR','154','Europe/Athens');
insert into ml_timezones (countrycode,id,name) values ('GS','155','Atlantic/South_Georgia');
insert into ml_timezones (countrycode,id,name) values ('GT','156','America/Guatemala');
insert into ml_timezones (countrycode,id,name) values ('GU','157','Pacific/Guam');
insert into ml_timezones (countrycode,id,name) values ('GW','158','Africa/Bissau');
insert into ml_timezones (countrycode,id,name) values ('GY','159','America/Guyana');
insert into ml_timezones (countrycode,id,name) values ('HK','160','Asia/Hong_Kong');
insert into ml_timezones (countrycode,id,name) values ('HN','161','America/Tegucigalpa');
insert into ml_timezones (countrycode,id,name) values ('HR','162','Europe/Zagreb');
insert into ml_timezones (countrycode,id,name) values ('HT','163','America/Port-au-Prince');
insert into ml_timezones (countrycode,id,name) values ('HU','164','Europe/Budapest');
insert into ml_timezones (countrycode,id,name) values ('ID','165','Asia/Jakarta');
insert into ml_timezones (countrycode,id,name) values ('ID','166','Asia/Pontianak');
insert into ml_timezones (countrycode,id,name) values ('ID','167','Asia/Ujung_Pandang');
insert into ml_timezones (countrycode,id,name) values ('ID','168','Asia/Jayapura');
insert into ml_timezones (countrycode,id,name) values ('IE','169','Europe/Dublin');
insert into ml_timezones (countrycode,id,name) values ('IL','170','Asia/Jerusalem');
insert into ml_timezones (countrycode,id,name) values ('IN','171','Asia/Calcutta');
insert into ml_timezones (countrycode,id,name) values ('IO','172','Indian/Chagos');
insert into ml_timezones (countrycode,id,name) values ('IQ','173','Asia/Baghdad');
insert into ml_timezones (countrycode,id,name) values ('IR','174','Asia/Tehran');
insert into ml_timezones (countrycode,id,name) values ('IS','175','Atlantic/Reykjavik');
insert into ml_timezones (countrycode,id,name) values ('IT','176','Europe/Rome');
insert into ml_timezones (countrycode,id,name) values ('JM','177','America/Jamaica');
insert into ml_timezones (countrycode,id,name) values ('JO','178','Asia/Amman');
insert into ml_timezones (countrycode,id,name) values ('JP','179','Asia/Tokyo');
insert into ml_timezones (countrycode,id,name) values ('KE','180','Africa/Nairobi');
insert into ml_timezones (countrycode,id,name) values ('KG','181','Asia/Bishkek');
insert into ml_timezones (countrycode,id,name) values ('KH','182','Asia/Phnom_Penh');
insert into ml_timezones (countrycode,id,name) values ('KI','183','Pacific/Tarawa');
insert into ml_timezones (countrycode,id,name) values ('KI','184','Pacific/Enderbury');
insert into ml_timezones (countrycode,id,name) values ('KI','185','Pacific/Kiritimati');
insert into ml_timezones (countrycode,id,name) values ('KM','186','Indian/Comoro');
insert into ml_timezones (countrycode,id,name) values ('KN','187','America/St_Kitts');
insert into ml_timezones (countrycode,id,name) values ('KP','188','Asia/Pyongyang');
insert into ml_timezones (countrycode,id,name) values ('KR','189','Asia/Seoul');
insert into ml_timezones (countrycode,id,name) values ('KW','190','Asia/Kuwait');
insert into ml_timezones (countrycode,id,name) values ('KY','191','America/Cayman');
insert into ml_timezones (countrycode,id,name) values ('KZ','192','Asia/Almaty');
insert into ml_timezones (countrycode,id,name) values ('KZ','193','Asia/Aqtobe');
insert into ml_timezones (countrycode,id,name) values ('KZ','194','Asia/Aqtau');
insert into ml_timezones (countrycode,id,name) values ('LA','195','Asia/Vientiane');
insert into ml_timezones (countrycode,id,name) values ('LB','196','Asia/Beirut');
insert into ml_timezones (countrycode,id,name) values ('LC','197','America/St_Lucia');
insert into ml_timezones (countrycode,id,name) values ('LI','198','Europe/Vaduz');
insert into ml_timezones (countrycode,id,name) values ('LK','199','Asia/Colombo');
insert into ml_timezones (countrycode,id,name) values ('LR','200','Africa/Monrovia');
insert into ml_timezones (countrycode,id,name) values ('LS','201','Africa/Maseru');
insert into ml_timezones (countrycode,id,name) values ('LT','202','Europe/Vilnius');
insert into ml_timezones (countrycode,id,name) values ('LU','203','Europe/Luxembourg');
insert into ml_timezones (countrycode,id,name) values ('LV','204','Europe/Riga');
insert into ml_timezones (countrycode,id,name) values ('LY','205','Africa/Tripoli');
insert into ml_timezones (countrycode,id,name) values ('MA','206','Africa/Casablanca');
insert into ml_timezones (countrycode,id,name) values ('MC','207','Europe/Monaco');
insert into ml_timezones (countrycode,id,name) values ('MD','208','Europe/Chisinau');
insert into ml_timezones (countrycode,id,name) values ('MG','209','Indian/Antananarivo');
insert into ml_timezones (countrycode,id,name) values ('MH','210','Pacific/Majuro');
insert into ml_timezones (countrycode,id,name) values ('MH','211','Pacific/Kwajalein');
insert into ml_timezones (countrycode,id,name) values ('MK','212','Europe/Skopje');
insert into ml_timezones (countrycode,id,name) values ('ML','213','Africa/Bamako');
insert into ml_timezones (countrycode,id,name) values ('ML','214','Africa/Timbuktu');
insert into ml_timezones (countrycode,id,name) values ('MM','215','Asia/Rangoon');
insert into ml_timezones (countrycode,id,name) values ('MN','216','Asia/Ulaanbaatar');
insert into ml_timezones (countrycode,id,name) values ('MN','217','Asia/Hovd');
insert into ml_timezones (countrycode,id,name) values ('MO','218','Asia/Macao');
insert into ml_timezones (countrycode,id,name) values ('MP','219','Pacific/Saipan');
insert into ml_timezones (countrycode,id,name) values ('MQ','220','America/Martinique');
insert into ml_timezones (countrycode,id,name) values ('MR','221','Africa/Nouakchott');
insert into ml_timezones (countrycode,id,name) values ('MS','222','America/Montserrat');
insert into ml_timezones (countrycode,id,name) values ('MT','223','Europe/Malta');
insert into ml_timezones (countrycode,id,name) values ('MU','224','Indian/Mauritius');
insert into ml_timezones (countrycode,id,name) values ('MV','225','Indian/Maldives');
insert into ml_timezones (countrycode,id,name) values ('MW','226','Africa/Blantyre');
insert into ml_timezones (countrycode,id,name) values ('MX','227','America/Mexico_City');
insert into ml_timezones (countrycode,id,name) values ('MX','228','America/Cancun');
insert into ml_timezones (countrycode,id,name) values ('MX','229','America/Merida');
insert into ml_timezones (countrycode,id,name) values ('MX','230','America/Monterrey');
insert into ml_timezones (countrycode,id,name) values ('MX','231','America/Mazatlan');
insert into ml_timezones (countrycode,id,name) values ('MX','232','America/Chihuahua');
insert into ml_timezones (countrycode,id,name) values ('MX','233','America/Hermosillo');
insert into ml_timezones (countrycode,id,name) values ('MX','234','America/Tijuana');
insert into ml_timezones (countrycode,id,name) values ('MY','235','Asia/Kuala_Lumpur');
insert into ml_timezones (countrycode,id,name) values ('MY','236','Asia/Kuching');
insert into ml_timezones (countrycode,id,name) values ('MZ','237','Africa/Maputo');
insert into ml_timezones (countrycode,id,name) values ('NA','238','Africa/Windhoek');
insert into ml_timezones (countrycode,id,name) values ('NC','239','Pacific/Noumea');
insert into ml_timezones (countrycode,id,name) values ('NE','240','Africa/Niamey');
insert into ml_timezones (countrycode,id,name) values ('NF','241','Pacific/Norfolk');
insert into ml_timezones (countrycode,id,name) values ('NG','242','Africa/Lagos');
insert into ml_timezones (countrycode,id,name) values ('NI','243','America/Managua');
insert into ml_timezones (countrycode,id,name) values ('NL','244','Europe/Amsterdam');
insert into ml_timezones (countrycode,id,name) values ('NO','245','Europe/Oslo');
insert into ml_timezones (countrycode,id,name) values ('NP','246','Asia/Katmandu');
insert into ml_timezones (countrycode,id,name) values ('NR','247','Pacific/Nauru');
insert into ml_timezones (countrycode,id,name) values ('NU','248','Pacific/Niue');
insert into ml_timezones (countrycode,id,name) values ('NZ','249','Pacific/Auckland');
insert into ml_timezones (countrycode,id,name) values ('NZ','250','Pacific/Chatham');
insert into ml_timezones (countrycode,id,name) values ('OM','251','Asia/Muscat');
insert into ml_timezones (countrycode,id,name) values ('PA','252','America/Panama');
insert into ml_timezones (countrycode,id,name) values ('PE','253','America/Lima');
insert into ml_timezones (countrycode,id,name) values ('PF','254','Pacific/Tahiti');
insert into ml_timezones (countrycode,id,name) values ('PF','255','Pacific/Marquesas');
insert into ml_timezones (countrycode,id,name) values ('PF','256','Pacific/Gambier');
insert into ml_timezones (countrycode,id,name) values ('PG','257','Pacific/Port_Moresby');
insert into ml_timezones (countrycode,id,name) values ('PH','258','Asia/Manila');
insert into ml_timezones (countrycode,id,name) values ('PK','259','Asia/Karachi');
insert into ml_timezones (countrycode,id,name) values ('PL','260','Europe/Warsaw');
insert into ml_timezones (countrycode,id,name) values ('PM','261','America/Miquelon');
insert into ml_timezones (countrycode,id,name) values ('PN','262','Pacific/Pitcairn');
insert into ml_timezones (countrycode,id,name) values ('PR','263','America/Puerto_Rico');
insert into ml_timezones (countrycode,id,name) values ('PS','264','Asia/Gaza');
insert into ml_timezones (countrycode,id,name) values ('PT','265','Europe/Lisbon');
insert into ml_timezones (countrycode,id,name) values ('PT','266','Atlantic/Madeira');
insert into ml_timezones (countrycode,id,name) values ('PT','267','Atlantic/Azores');
insert into ml_timezones (countrycode,id,name) values ('PW','268','Pacific/Palau');
insert into ml_timezones (countrycode,id,name) values ('PY','269','America/Asuncion');
insert into ml_timezones (countrycode,id,name) values ('QA','270','Asia/Qatar');
insert into ml_timezones (countrycode,id,name) values ('RE','271','Indian/Reunion');
insert into ml_timezones (countrycode,id,name) values ('RO','272','Europe/Bucharest');
insert into ml_timezones (countrycode,id,name) values ('RU','273','Europe/Kaliningrad');
insert into ml_timezones (countrycode,id,name) values ('RU','274','Europe/Moscow');
insert into ml_timezones (countrycode,id,name) values ('RU','275','Europe/Samara');
insert into ml_timezones (countrycode,id,name) values ('RU','276','Asia/Yekaterinburg');
insert into ml_timezones (countrycode,id,name) values ('RU','277','Asia/Omsk');
insert into ml_timezones (countrycode,id,name) values ('RU','278','Asia/Novosibirsk');
insert into ml_timezones (countrycode,id,name) values ('RU','279','Asia/Krasnoyarsk');
insert into ml_timezones (countrycode,id,name) values ('RU','280','Asia/Irkutsk');
insert into ml_timezones (countrycode,id,name) values ('RU','281','Asia/Yakutsk');
insert into ml_timezones (countrycode,id,name) values ('RU','282','Asia/Vladivostok');
insert into ml_timezones (countrycode,id,name) values ('RU','283','Asia/Magadan');
insert into ml_timezones (countrycode,id,name) values ('RU','284','Asia/Kamchatka');
insert into ml_timezones (countrycode,id,name) values ('RU','285','Asia/Anadyr');
insert into ml_timezones (countrycode,id,name) values ('RW','286','Africa/Kigali');
insert into ml_timezones (countrycode,id,name) values ('SA','287','Asia/Riyadh');
insert into ml_timezones (countrycode,id,name) values ('SB','288','Pacific/Guadalcanal');
insert into ml_timezones (countrycode,id,name) values ('SC','289','Indian/Mahe');
insert into ml_timezones (countrycode,id,name) values ('SD','290','Africa/Khartoum');
insert into ml_timezones (countrycode,id,name) values ('SE','291','Europe/Stockholm');
insert into ml_timezones (countrycode,id,name) values ('SG','292','Asia/Singapore');
insert into ml_timezones (countrycode,id,name) values ('SH','293','Atlantic/St_Helena');
insert into ml_timezones (countrycode,id,name) values ('SI','294','Europe/Ljubljana');
insert into ml_timezones (countrycode,id,name) values ('SJ','295','Arctic/Longyearbyen');
insert into ml_timezones (countrycode,id,name) values ('SJ','296','Atlantic/Jan_Mayen');
insert into ml_timezones (countrycode,id,name) values ('SK','297','Europe/Bratislava');
insert into ml_timezones (countrycode,id,name) values ('SL','298','Africa/Freetown');
insert into ml_timezones (countrycode,id,name) values ('SM','299','Europe/San_Marino');
insert into ml_timezones (countrycode,id,name) values ('SN','300','Africa/Dakar');
insert into ml_timezones (countrycode,id,name) values ('SO','301','Africa/Mogadishu');
insert into ml_timezones (countrycode,id,name) values ('SR','302','America/Paramaribo');
insert into ml_timezones (countrycode,id,name) values ('ST','303','Africa/Sao_Tome');
insert into ml_timezones (countrycode,id,name) values ('SV','304','America/El_Salvador');
insert into ml_timezones (countrycode,id,name) values ('SY','305','Asia/Damascus');
insert into ml_timezones (countrycode,id,name) values ('SZ','306','Africa/Mbabane');
insert into ml_timezones (countrycode,id,name) values ('TC','307','America/Grand_Turk');
insert into ml_timezones (countrycode,id,name) values ('TD','308','Africa/Ndjamena');
insert into ml_timezones (countrycode,id,name) values ('TF','309','Indian/Kerguelen');
insert into ml_timezones (countrycode,id,name) values ('TG','310','Africa/Lome');
insert into ml_timezones (countrycode,id,name) values ('TH','311','Asia/Bangkok');
insert into ml_timezones (countrycode,id,name) values ('TJ','312','Asia/Dushanbe');
insert into ml_timezones (countrycode,id,name) values ('TK','313','Pacific/Fakaofo');
insert into ml_timezones (countrycode,id,name) values ('TM','314','Asia/Ashgabat');
insert into ml_timezones (countrycode,id,name) values ('TN','315','Africa/Tunis');
insert into ml_timezones (countrycode,id,name) values ('TO','316','Pacific/Tongatapu');
insert into ml_timezones (countrycode,id,name) values ('TP','317','Asia/Dili');
insert into ml_timezones (countrycode,id,name) values ('TR','318','Europe/Istanbul');
insert into ml_timezones (countrycode,id,name) values ('TT','319','America/Port_of_Spain');
insert into ml_timezones (countrycode,id,name) values ('TV','320','Pacific/Funafuti');
insert into ml_timezones (countrycode,id,name) values ('TW','321','Asia/Taipei');
insert into ml_timezones (countrycode,id,name) values ('TZ','322','Africa/Dar_es_Salaam');
insert into ml_timezones (countrycode,id,name) values ('UA','323','Europe/Kiev');
insert into ml_timezones (countrycode,id,name) values ('UA','324','Europe/Uzhgorod');
insert into ml_timezones (countrycode,id,name) values ('UA','325','Europe/Zaporozhye');
insert into ml_timezones (countrycode,id,name) values ('UA','326','Europe/Simferopol');
insert into ml_timezones (countrycode,id,name) values ('UG','327','Africa/Kampala');
insert into ml_timezones (countrycode,id,name) values ('UM','328','Pacific/Johnston');
insert into ml_timezones (countrycode,id,name) values ('UM','329','Pacific/Midway');
insert into ml_timezones (countrycode,id,name) values ('UM','330','Pacific/Wake');
insert into ml_timezones (countrycode,id,name) values ('US','331','America/New_York');
insert into ml_timezones (countrycode,id,name) values ('US','332','America/Detroit');
insert into ml_timezones (countrycode,id,name) values ('US','333','America/Louisville');
insert into ml_timezones (countrycode,id,name) values ('US','334','America/Kentucky/Monticello');
insert into ml_timezones (countrycode,id,name) values ('US','335','America/Indianapolis');
insert into ml_timezones (countrycode,id,name) values ('US','336','America/Indiana/Marengo');
insert into ml_timezones (countrycode,id,name) values ('US','337','America/Indiana/Knox');
insert into ml_timezones (countrycode,id,name) values ('US','338','America/Indiana/Vevay');
insert into ml_timezones (countrycode,id,name) values ('US','339','America/Chicago');
insert into ml_timezones (countrycode,id,name) values ('US','340','America/Menominee');
insert into ml_timezones (countrycode,id,name) values ('US','341','America/Denver');
insert into ml_timezones (countrycode,id,name) values ('US','342','America/Boise');
insert into ml_timezones (countrycode,id,name) values ('US','343','America/Shiprock');
insert into ml_timezones (countrycode,id,name) values ('US','344','America/Phoenix');
insert into ml_timezones (countrycode,id,name) values ('US','345','America/Los_Angeles');
insert into ml_timezones (countrycode,id,name) values ('US','346','America/Anchorage');
insert into ml_timezones (countrycode,id,name) values ('US','347','America/Juneau');
insert into ml_timezones (countrycode,id,name) values ('US','348','America/Yakutat');
insert into ml_timezones (countrycode,id,name) values ('US','349','America/Nome');
insert into ml_timezones (countrycode,id,name) values ('US','350','America/Adak');
insert into ml_timezones (countrycode,id,name) values ('US','351','Pacific/Honolulu');
insert into ml_timezones (countrycode,id,name) values ('UY','352','America/Montevideo');
insert into ml_timezones (countrycode,id,name) values ('UZ','353','Asia/Samarkand');
insert into ml_timezones (countrycode,id,name) values ('UZ','354','Asia/Tashkent');
insert into ml_timezones (countrycode,id,name) values ('VA','355','Europe/Vatican');
insert into ml_timezones (countrycode,id,name) values ('VC','356','America/St_Vincent');
insert into ml_timezones (countrycode,id,name) values ('VE','357','America/Caracas');
insert into ml_timezones (countrycode,id,name) values ('VG','358','America/Tortola');
insert into ml_timezones (countrycode,id,name) values ('VI','359','America/St_Thomas');
insert into ml_timezones (countrycode,id,name) values ('VN','360','Asia/Saigon');
insert into ml_timezones (countrycode,id,name) values ('VU','361','Pacific/Efate');
insert into ml_timezones (countrycode,id,name) values ('WF','362','Pacific/Wallis');
insert into ml_timezones (countrycode,id,name) values ('WS','363','Pacific/Apia');
insert into ml_timezones (countrycode,id,name) values ('YE','364','Asia/Aden');
insert into ml_timezones (countrycode,id,name) values ('YT','365','Indian/Mayotte');
insert into ml_timezones (countrycode,id,name) values ('YU','366','Europe/Belgrade');
insert into ml_timezones (countrycode,id,name) values ('ZA','367','Africa/Johannesburg');
insert into ml_timezones (countrycode,id,name) values ('ZM','368','Africa/Lusaka');
insert into ml_timezones (countrycode,id,name) values ('ZW','369','Africa/Harare');

commit work;
